version: '2'

services:
  api:
    image: api
    ports:
      - "5000:80"
    links:
      - rabbitmq
    build:
      context: ./Api
      dockerfile: Dockerfile
    args:
      buildno: 1

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672   #rabbitmq
      - 15672:15672 #management-ui