version: '2'

services:
  api:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      "com.microsoft.visualstudio.targetoperatingsystem=linux"
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "test.api.fmc.com"