version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  trafficgen:
    environment:
      - INTERVAL=100