version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev

  trafficgen:
    environment:
      - API_URL=http://api