version: '2'

services:
  api:
    image: api
    ports:
      - "5000:80"
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  trafficgenerator:
    image: trafficgenerator
    build:
      context: ./TrafficGenerator
      dockerfile: Dockerfile
    links:
      - api
    environment:
      - ENVIRONMENT=debug
      - API_URL=http://api/events