version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    image: api
    ports:
      - "5000:80"
    links:
      - rabbitmq
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=dev.api.cicdpocagents.westus.cloudapp.azure.com/


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672   #rabbitmq
      - 15672:15672 #management-ui