version: '2'

services:
  api:
    cpuset: 0,2
    mem_limit: 128m
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev

  trafficgen:
    cpuset: 0,2
    mem_limit: 32m
    environment:
      - INTERVAL_MIN=100
      - INTERVAL_MAX=1000