version: '3'

services:
  api:
    deploy:
      resources:
        limits:
          cpus: '0.02'
          memory: 32M
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev

  trafficgen:
    mem_limit: 32m
    environment:
      - INTERVAL_MIN=100
      - INTERVAL_MAX=1000