version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
      - MARATHON_APP_RESOURCE_MEM=32

  trafficgen:
    environment:
      - INTERVAL_MIN=100
      - INTERVAL_MAX=1000