version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev

  trafficgenerator:
    environment:
      - ENVIRONMENT=dev
      - API_URL=2ce0d031.api.internal:5000