version: '2'

services:
  api:
    image: api
    ports:
      - "5000:80"
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  trafficgen:
    image: trafficgen
    build:
      context: ./TrafficGen
      dockerfile: Dockerfile
    links:
      - api