version: '2'

services:
  api:
    image: api
    ports:
      - "5000:80"
    links:
      - rabbitmq
    build:
      context: ./Api
      dockerfile: Dockerfile
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development