version: '2'

services:
  api:
    image: api:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./Api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  elk:
    image: sebp/elk
    container_name: elk
    mem_limit: 4G
    ports:
      - 5601:5601 #kibana
      - 9200:9200 #elasticsearch
    environment:
      - LOGSTASH_START=1
      - KIBANA_START=1
    links:
      - rabbitmq
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672   #rabbitmq
      - 15672:15672 #management-ui