version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "dev.api.fmc.com"
      "MARATHON_APP_RESOURCE_MEM": 32
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev

  trafficgen:
    environment:
      - INTERVAL=100