version: '2'

services:
  api:
    labels:
      "HAPROXY_GROUP": "external"
      "HAPROXY_0_VHOST": "test.api.fmc.com"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test

  trafficgen:
    environment:
      - INTERVAL_MIN=100
      - INTERVAL_MAX=1000